name: Docker Compose

on:
  workflow_dispatch:
  # prevents useless startups
  # push:
  #   branches: ['main']
  # pull_request:
  #   branches: ['main']

jobs:
  Build_Docker_Compose:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: init
        uses: npm install

      - name: Run docker-compose
        run: npm test
