name: Start all tests

on:
  workflow_dispatch:
  # prevents useless startups
  # push:
  #   branches: ['main']
  # pull_request:
  #   branches: ['main']

jobs:
  Start_all_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: install all packages
        run: npm install

      - name: Run all tests
        run: npm test
